let names = ['Anastazja', 'Kuba', 'Rafal'];
console.log(names[1]);
names.push('Konrad');
console.log(names);
names.pop();
console.log(names);
names.unshift('Slawek');
console.log(names);
names.shift();
console.log(names);
console.log(names.length);
// console.log(names.join(" & "));
// console.log(names.reverse());
console.log(names.sort());
